[databases]
demo = host=postgresql port=5432 dbname=demo pool_mode=transaction

[pgbouncer]
listen_addr = 0.0.0.0
listen_port = 6432
auth_type = md5
auth_file = /etc/pgbouncer/userlist.txt

# Client Side SSL
client_tls_sslmode = require
client_tls_ca_file = /etc/pgbouncer/certs/ca.crt
client_tls_key_file = /etc/pgbouncer/certs/server.key
client_tls_cert_file = /etc/pgbouncer/certs/server.crt

# Server Side SSL
server_tls_sslmode = require
server_tls_ca_file = /etc/pgbouncer/certs/ca.crt

pool_mode = transaction
max_client_conn = 10000
default_pool_size = 10
min_pool_size = 4
reserve_pool_size = 5
max_db_connections = 40
logfile = /tmp/pgbouncer.log
pidfile = /tmp/pgbouncer.pid
admin_users = postgres
